name: Chore
description: Maintenance that is not a product feature
title: '[CHORE] '
labels: ['chore']
body:
  - type: textarea
    id: work
    attributes:
      label: Work requested
    validations:
      required: true
  - type: dropdown
    id: risk
    attributes:
      label: Risk
      options: [Low, Medium, High, Critical]
    validations:
      required: true
